### ISSUE TITLE
this.updater.enqueueCallback is not a function

### ISSUE THREAD

**Issue by carl-angelo** [Artear/ReactResumableJS#35]
![image](https://user-images.githubusercontent.com/28854416/60418682-24ac5c80-9c16-11e9-9d29-2a19074a306b.png)

Based on this https://github.com/facebook/react/issues/10320 , the react is not updated to its new version.

**Comment by rana-rajnikant** [comment]
Hi @carl-angelo,

I am also getting the same error while work with React 16.8.6 

Did you found any workaround to resolve the issue? 

Appreciate for your help.

**Comment by nikennovirasari** [comment]
![image](https://user-images.githubusercontent.com/15240514/76602243-1c464880-653d-11ea-88a9-7098e8c1f447.png)
React 16.6.3

**Comment by shaunclark5649** [comment]
I am also getting this issue, it would be great to find a fix. Thanks

**Comment by jfrshd** [comment]
Did anyone find a solution?
